### ISSUE TITLE
Error while fetching Products from API

### ISSUE THREAD

**Issue by conradbekondo** [conradbekondo/inventory-api#12]
I get this error while trying to fetch data from the `GET /api/inventory/products` endpoint after updating to the latest docker image.

```java
org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type for: public abstract int ca.quickdo.springintro.repository.MovementsRepository.calculateTotalQuantityByProduct(java.lang.Integer)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:255) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at jdk.proxy2/jdk.proxy2.$Proxy116.calculateTotalQuantityByProduct(Unknown Source) ~[na:na]
        at ca.quickdo.springintro.controller.InventoryController.lambda$getProducts$0(InventoryController.java:66) ~[classes!/:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
        at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003) ~[na:na]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
```

**Comment by IlorsonDel** [comment]
I went through and I understood that, the error message suggests that there is an issue with the return type of the calculateTotalQuantityByProduct method in the MovementsRepository. The method is defined to return an int primitive type, but the advice (interceptor) used in the AOP invocation is returning a null value, which does not match the primitive return type.

So I modified the calculateTotalQuantityByProduct method to return an integer

**Comment by conradbekondo** [comment]
@IlorsonDel you can just use `Optional<Integer>` as return type

**Comment by IlorsonDel** [comment]
Thanks sir, I did so, and pushed back

**Comment by conradbekondo** [comment]
@IlorsonDel  did you build the application on your local machine before pushing?

https://github.com/conradbekondo/inventory-api/actions/runs/8910454921/job/24469764276#step:5:27

**Comment by IlorsonDel** [comment]
I build it and solve the remaining errors. Am just from pushing it back, you can look at it !
